### ISSUE TITLE
图片识别失败

### ISSUE THREAD

**Issue by cluda01** [MonsterNone/618-miao#1]
手机分辨率1920x2160，是否可以自己截图替换到相应位置？对分辨率有没有要求？

**Comment by MonsterNone** [comment]
理论上来说对分辨率没有要求，自己截图替换到文件下下对应的图片(文件名一致，具体内容看图)。如果无法解决请提交识别失败页面的截图

**Comment by MonsterNone** [comment]
现在修改了识别区域，下载最新的test.js(或者压缩包)并替换原来的应该没问题了
