### ISSUE TITLE
去逛店的入口没了，用不起来

### ISSUE THREAD

**Issue by OilLyu** [MonsterNone/618-miao#2]
现在领喵币菜单里没有了去逛店的入口，需要下滑到下面点击各个店铺进去领币，这样还可以再更新下脚本用吗

**Comment by MonsterNone** [comment]
下面的一堆店铺暂时想不到好的图像识别方法，只能根据分辨率计算相对坐标（v0.0.2版本）。已经更新了README。

**Comment by daxinnan** [comment]
根据分辨率计算相对坐标有实现的吗

**Comment by MonsterNone** [comment]
> 根据分辨率计算相对坐标有实现的吗

有。项目中的try.js

**Comment by MonsterNone** [comment]
已修复。通过合合卡入口逛店。
